// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpnG4pMlNlIwXElil1p7XMJeVBeDcYjY',
    appId: '1:1074673473332:web:94c85c3f37589ffe89f761',
    messagingSenderId: '1074673473332',
    projectId: 'databasegtr-2e57c',
    authDomain: 'databasegtr-2e57c.firebaseapp.com',
    storageBucket: 'databasegtr-2e57c.firebasestorage.app',
    measurementId: 'G-Y8Q9K8FJ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn0BSWpxkmlQ8YUamDGxatCsOOTC2XLww',
    appId: '1:1074673473332:android:f395912f44d0ad3789f761',
    messagingSenderId: '1074673473332',
    projectId: 'databasegtr-2e57c',
    storageBucket: 'databasegtr-2e57c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2x6nAYA3DpbjNjNTs5hDs7rrJybzQMIU',
    appId: '1:1074673473332:ios:edc3ab43ee7221fd89f761',
    messagingSenderId: '1074673473332',
    projectId: 'databasegtr-2e57c',
    storageBucket: 'databasegtr-2e57c.firebasestorage.app',
    iosBundleId: 'com.example.mini008',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2x6nAYA3DpbjNjNTs5hDs7rrJybzQMIU',
    appId: '1:1074673473332:ios:edc3ab43ee7221fd89f761',
    messagingSenderId: '1074673473332',
    projectId: 'databasegtr-2e57c',
    storageBucket: 'databasegtr-2e57c.firebasestorage.app',
    iosBundleId: 'com.example.mini008',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxpnG4pMlNlIwXElil1p7XMJeVBeDcYjY',
    appId: '1:1074673473332:web:0ae4419f8410d17e89f761',
    messagingSenderId: '1074673473332',
    projectId: 'databasegtr-2e57c',
    authDomain: 'databasegtr-2e57c.firebaseapp.com',
    storageBucket: 'databasegtr-2e57c.firebasestorage.app',
    measurementId: 'G-H8Z024FNKZ',
  );
}
